version: "3"

services:
  api-gateway:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - service1
      - service2
      - service3
  
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=react.local

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret

  service1:
    build: ./users
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=users.local
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret

  service2:
    build: ./companies
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=companies.local
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret

  service3:
    build: ./employees
    ports:
      - "8002:8002"
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=employees.local
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
